# -*- coding: utf-8 -*-
"""Sriram Gopalan G-CODTECH Task 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B8nNHN15LeAXCYkfyNUPlIf0USmv9NX7
"""

# Name:SRIRAM GOPALAN G
# TASK 1:BIG DATA ANALYSIS

# Task 1 - Heart Disease Dataset Analysis

pip install pyspark pandas matplotlib seaborn

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, avg, max, min, count
import matplotlib.pyplot as plt

spark = SparkSession.builder \
    .appName("Heart Disease Analysis") \
    .getOrCreate()

file_path = "heart.csv"
data = spark.read.csv(file_path, header=True, inferSchema=True)

print("Dataset Schema:")
data.printSchema()

print("Sample Data:")
data.show(5)

total_records = data.count()
print(f"Total number of records: {total_records}")

print("Distribution of Heart Disease (target):")
data.groupBy("target").count().show()

print("Average Age of Patients with and without Heart Disease:")
avg_age = data.groupBy("target").agg(avg(col("age")).alias("Average Age"))
avg_age.show()

if "cp" in data.columns:
    print("Distribution of Chest Pain Types:")
    data.groupBy("cp").count().orderBy(col("count").desc()).show()

filtered_data = data.filter((col("age") > 60) & (col("target") == 1))
print("Patients older than 60 with heart disease:")
filtered_data.show(5)

filtered_pandas = filtered_data.toPandas()

plt.figure(figsize=(10, 6))
filtered_pandas["age"].hist(bins=10)
plt.title("Age Distribution of Patients with Heart Disease (Age > 60)")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()
spark.stop()